Repository Shannon-Data/ShannonBase, pull requests merged in 2024-05, with the labels that each got.

#166 Develop
  .clang-format
  sql/sql_table.cc
  storage/rapid_engine/CMakeLists.txt
  storage/rapid_engine/compress/algorithms.cpp
  storage/rapid_engine/compress/algorithms.h
  storage/rapid_engine/compress/dictionary/dictionary.cpp
  storage/rapid_engine/compress/dictionary/dictionary.h
  storage/rapid_engine/handler/ha_shannon_rapid.cc
  storage/rapid_engine/imcs/chunk.cpp
  storage/rapid_engine/imcs/chunk.h
  storage/rapid_engine/imcs/cu.cpp
  storage/rapid_engine/imcs/cu.h
  storage/rapid_engine/imcs/imcs.cpp
  storage/rapid_engine/imcs/imcs.h
  storage/rapid_engine/imcs/index/art.cpp
  storage/rapid_engine/imcs/index/art.h
  storage/rapid_engine/include/rapid_arch_inf.h
  storage/rapid_engine/include/rapid_const.h
  storage/rapid_engine/optimizer/optimizer.cpp
  storage/rapid_engine/optimizer/optimizer.h
  storage/rapid_engine/optimizer/rules/const_fold_rule.cpp
  storage/rapid_engine/populate/log_commons.h
  storage/rapid_engine/populate/log_parser.cpp
  storage/rapid_engine/populate/log_reader.cpp
  storage/rapid_engine/populate/log_reader.h
  storage/rapid_engine/populate/populate.cpp
  storage/rapid_engine/populate/populate.h
  storage/rapid_engine/reader/csv_reader.cpp
  storage/rapid_engine/reader/csv_reader.h
  storage/rapid_engine/reader/imcs_reader.cpp
  storage/rapid_engine/reader/imcs_reader.h
  storage/rapid_engine/reader/parquet_reader.cpp
  storage/rapid_engine/reader/parquet_reader.h
  storage/rapid_engine/reader/reader.h
  storage/rapid_engine/trx/transaction.h
  storage/rapid_engine/utils/utils.cpp
  storage/rapid_engine/utils/utils.h
Labels: enhancement, feature

#170 feat(shannon):impr the perfomrance of rapid
  mysql-test/suite/secondary_engine/t/shannon_case1.test
  storage/innobase/mtr/mtr0mtr.cc
  storage/rapid_engine/compress/algorithms.cpp
  storage/rapid_engine/compress/algorithms.h
  storage/rapid_engine/compress/dictionary/dictionary.cpp
  storage/rapid_engine/include/rapid_const.h
  storage/rapid_engine/populate/log_parser.cpp
  storage/rapid_engine/populate/log_parser.h
  storage/rapid_engine/reader/imcs_reader.cpp
Labels: enhancement, feature

#174 Refactor mtr rapid
  .github/workflows/pull-requests.yaml
  mysql-test/suite/secondary_engine/r/shannon_case1.result
  mysql-test/suite/secondary_engine/r/shannon_case2.result
  mysql-test/suite/secondary_engine/r/shannon_case3.result
  mysql-test/suite/secondary_engine/r/shannon_change_pop.result
  mysql-test/suite/secondary_engine/r/shannon_insert_batch2.result
  mysql-test/suite/secondary_engine/t/shannon_case1.test.bak
  mysql-test/suite/secondary_engine/t/shannon_case2.test
  mysql-test/suite/secondary_engine/t/shannon_case3.test
  mysql-test/suite/secondary_engine/t/shannon_change_pop.test
  mysql-test/suite/secondary_engine/t/shannon_create_table.test.bak
  mysql-test/suite/secondary_engine/t/shannon_insert_batch.test
  mysql-test/suite/secondary_engine/t/shannon_insert_batch2.test
  mysql-test/suite/secondary_engine/t/shannon_load.test
  mysql-test/suite/secondary_engine/t/shannon_query.test
  mysql-test/suite/secondary_engine/t/shannon_tpch.test.bak
  storage/innobase/log/log0buf.cc
  storage/innobase/mtr/mtr0mtr.cc
  storage/rapid_engine/handler/ha_shannon_rapid.cc
  storage/rapid_engine/populate/log_parser.cpp
  storage/rapid_engine/populate/populate.cpp
  storage/rapid_engine/populate/populate.h
Labels: feature, testing

#184 feat(shannon): new cond for loaded tables
  ml/ml_regression.cpp
  storage/innobase/handler/ha_innodb.cc
  storage/innobase/row/row0ins.cc
  storage/perfschema/table_rpd_table_id.cc
  storage/rapid_engine/handler/ha_shannon_rapid.h
  storage/rapid_engine/imcs/imcs.cpp
  storage/rapid_engine/populate/log_parser.cpp
  storage/rapid_engine/populate/populate.cpp
Labels: feature

#189 feat(shannon):base funcs for parallel scan
  sql/handler.h
  sql/pq_range.h
  storage/innobase/handler/ha_innodb.h
  storage/innobase/handler/handler0alter.cc
  storage/innobase/include/btr0pcur.h
  storage/innobase/include/data0data.h
  storage/innobase/include/db0err.h
  storage/innobase/include/read0read.h
  storage/innobase/include/read0types.h
  storage/innobase/include/rem0cmp.h
  storage/innobase/include/row0mysql.h
  storage/innobase/include/row0pread.h
  storage/innobase/include/row0sel.h
  storage/innobase/include/srv0srv.h
  storage/innobase/include/trx0trx.h
  storage/innobase/read/read0read.cc
  storage/innobase/rem/rem0cmp.cc
  storage/innobase/row/row0pread.cc
  storage/innobase/row/row0sel.cc
  storage/innobase/srv/srv0srv.cc
  storage/innobase/trx/trx0trx.cc
  storage/innobase/ut/ut0ut.cc
Labels: feature

#190 feat(shannon):parallel scan
  share/messages_to_clients.txt
  sql/CMakeLists.txt
  sql/handler.cc
  sql/handler.h
  sql/psi_memory_key.cc
  sql/psi_memory_key.h
  sql/sql_class.cc
  sql/sql_class.h
  sql/sql_pq_condition.cc
  sql/sql_pq_condition.h
  sql/sql_pq_global.h
  sql/sql_pq_range.h
  storage/innobase/handler/ha_innodb.cc
  storage/innobase/handler/handler0alter.cc
  storage/innobase/include/row0pread.h
Labels: feature
