Repository Shannon-Data/ShannonBase, pull requests merged in 2025-07, with the labels that each got.

#422 feat(shannon): to enable thread pool for co-routine
  README.md
  storage/rapid_engine/imcs/imcs.cpp
  storage/rapid_engine/imcs/imcs.h
  storage/rapid_engine/include/rapid_object.h
  storage/rapid_engine/populate/log_parser.cpp
  storage/rapid_engine/populate/log_parser.h
  storage/rapid_engine/populate/populate.cpp
Labels: enhancement, performance

#429 feat(rapid): to fixup memory usage management
  mysql-test/suite/secondary_engine/r/shannon_case6.result
  mysql-test/suite/secondary_engine/t/shannon_case6.test
  storage/rapid_engine/handler/ha_shannon_rapid.cc
  storage/rapid_engine/imcs/chunk.cpp
  storage/rapid_engine/imcs/chunk.h
  storage/rapid_engine/imcs/cu.cpp
  storage/rapid_engine/imcs/cu.h
  storage/rapid_engine/imcs/data_table.h
  storage/rapid_engine/imcs/imcs.cpp
  storage/rapid_engine/imcs/index/iterator.h
  storage/rapid_engine/include/rapid_status.h
  storage/rapid_engine/populate/log_parser.cpp
Labels: enhancement

#436 merge develop to main
  CMakeLists.txt
  README.md
  cmake/FindONNXRuntime.cmake
  storage/rapid_engine/CMakeLists.txt
  storage/rapid_engine/imcs/chunk.cpp
  storage/rapid_engine/imcs/chunk.h
  storage/rapid_engine/persistence/persistence.cpp
  storage/rapid_engine/persistence/persistence.h
  storage/rapid_engine/utils/utils.h
Labels: enhancement, feature

#439 feat(rapid):for performance tuning
  storage/rapid_engine/include/rapid_const.h
  storage/rapid_engine/populate/log_parser.cpp
  storage/rapid_engine/populate/log_parser.h
  storage/rapid_engine/utils/concurrent.h
  storage/rapid_engine/utils/cpu.h
  storage/rapid_engine/utils/utils.h
Labels: enhancement, performance

#441 feat(rapid): add llm-models directory to store the llm models
  CMakeLists.txt
  cmake/FindONNXRuntime.cmake
  extra/llm-models/readme.txt
  mysql-test/r/mysqld--help-notwin.result
  sql/mysqld.cc
  sql/mysqld.h
  sql/options_mysqld.h
  storage/rapid_engine/include/rapid_const.h
Labels: enhancement, feature

#442 feat(rapid): add README.md for ONNX toolswq
  extra/llm-models/README.md
  extra/llm-models/readme.txt
Labels: documentation

#443 feat(readme):to update readme
  README.md
Labels: documentation

#456 feat(rapid):to check params
  .github/workflows/nightly.yaml
  .github/workflows/pull-requests.yaml
  .github/workflows/weekly.yaml
  mysql-test/suite/secondary_engine/r/shannon_params.result
  mysql-test/suite/secondary_engine/t/shannon_params.test
  storage/rapid_engine/handler/ha_shannon_rapid.cc
Labels: feature
